### ISSUE TITLE
Antialias

### ISSUE THREAD

**Issue by Akintos** [atoring/frostpunk_mod#1]
Thank you for amazing tool.

Is there any progress on antialias?

**Comment by atoring** [comment]
https://github.com/atoring/frostpunk_mod/blob/master/binfont/data/font_0.png
Like this png, if texture is blurred, anti-aliasing will be enabled.
Blurring is necessary greatly.
I processed it using photoshop.
I am hoping to create scripts to process automatically using python imaging.
