### ISSUE TITLE
Broken output

### ISSUE THREAD

**Issue by Akintos** [atoring/frostpunk_mod#2]
When I run `decode.py`, it outputs broken image like [this](https://imgur.com/a/P6JiWJB)(cropped image).

Is it my environment's problem?

Using python 3.6.5 64bit, Pillow 5.1.0, Windows 10 64bit.

**Comment by atoring** [comment]
That is a correct texture.
If you create a binfont from that texture, the game will work correctly.
I think that using such a DDS texture tool, such data will be created.
I'm sorry, I do not know why such data.

**Comment by Akintos** [comment]
Oh I thought this is wrong output since the file in this repo was clean.
Thank you for response.

Also, is it okay to use tool for Korean translation?

**Comment by atoring** [comment]
In the meantime, I'd like to investigate the data.
About translation, it is all right. Good luck!
